### ISSUE TITLE
the `/online-users` is not working correctly

### ISSUE THREAD

**Issue by Anazzlia** [rodrigo-ceccato/easyPomo#48]
hey:) I just noticed that the `/online-users` **don't show all the active users**
For example: today Leo and I were using pomo and only showed "_1 in the last 5s_"... we believe that "_1_" was my computer because Lucas was also using pomo, but through script 
I think the users using the last version of the script are not showing online, or might be a version problem, I don't know what could be causing it

**Comment by rodrigo-ceccato** [comment]
If you are running it from the same network, /online-users is not able to count each of you as distinct users, since they all hit the endpoint with the same external IP;

if that is the case, this is the expected behavior, if not, feel free to open again
